FROM tensorflow/tensorflow:1.15.0-py3

RUN apt-get -y update && \
  apt-get -y install libsm6 libxrender-dev libxext6 libcap-dev ffmpeg git && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/* /tmp/*

WORKDIR /workspace/mot

ADD . /workspace/mot

RUN pip3 install .

RUN ./tests/prepare_tests.sh

ENTRYPOINT ["tests/run_tests.sh"]
