FROM tensorflow/tensorflow:1.15.0-py3

RUN apt-get -y update && \
  apt-get -y install libsm6 libxrender-dev libxext6 libcap-dev ffmpeg git && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/* /tmp/*

WORKDIR workspace

ADD . mot

RUN cd mot && \
  pip3 install . && \
  pip3 install pytest>=5.3.0 pytest-cov>=2.8.1 && \
	python scripts/download_models_and_files.py && \
	pytest --cov mot tests/
